### PR TITLE
We've translated in Japanese for MapSwipe website

### PR DESCRIPTION
**Pull request by mapconcierge**
Please confirm our translations.
We wish, MapSwipe will support in Japanese language. :-)

Happy Mapping!

from YouthMappers AGU, and Furuhashi Laboratory team.

### CODE REVIEW

**Comment by laurentS** [comment]
Thank you so much @mapconcierge  and everyone, this is fantastic! We will think of a good way to make it public quickly.
Also, about translating the app itself, I am working on it, and it should be ready to translate very soon. We will use transifex https://www.transifex.com/mapswipe/mapswipe-app to manage translations. It would be awesome if you could help with translating it as well :)

**Comment by mapconcierge** [comment]
Thanks @laurentS !

Yes, we can contribute Map.Swipe apps translation in Japanese too :-)
When transifex can use mapswipe-app for Japanese, our team will join.

**Comment by jhenshall** [comment]
Thanks again for this @mapconcierge - amazing to have the site translated to Japanese! Sorry for the delay but we've been changing the workflow of deploying to the site, which has included running GitHub pages from the new `gh-pages` branch, rather than `master/docs`.

We're hoping to integrate Transifex to make translating the website more sustainable but we'd love to get what you've done live while we continue to work on this. ~~Could you please create a new PR to merge just your /jp directory to the new gh-pages repo?~~ Thank you!

**Comment by jhenshall** [comment]
Hi again @mapconcierge - sorry, but with the recent changes, we have been considering the options and **please ignore my request above**. Instead, I am going to integrate your changes into our workflow better and will get your changes public as soon as possible. I will will keep you updated. Thanks!

**Comment by jhenshall** [comment]
Hi @mapconcierge. I've just published your Japanese version to the live site. Thanks again to you and all that helped. Obviously there is currently no language switcher link but we are working on this alongside integrating Transifex.

**Pull request merged**
